services:
  postgres:
    image: postgres:18-alpine
    container_name: food-delivery-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"